image: nikolaik/python-nodejs:python3.8-nodejs10
cache:
  untracked: true
  paths:
    - node_modules/

stages:
  - setup
  - test 
  - build
  - deploy

setup:
  stage: setup
  script:
   - export PYTHONPATH=$PWD/backend/lib:$PYTHONPATH
   - npm i
  only:
    - master

test unit:
  stage: test
  script:
    - npm run test
  only:
    - master

test_ui:
  stage: test
  script:
    - npm run confidence-check --host=selenium__standalone-firefix
    - python test.py
  services:
    - selenium/standalone-firefox:latest
  script:
    - pip install selenium==3.3.0
    - wget https://github.com/mozilla/geckodriver/releases/download/v0.23.0/geckodriver-v0.23.0-linux64.tar.gz
    - sh -c 'tar -x geckodriver -zf geckodriver-v0.23.0-linux64.tar.gz -O > /usr/bin/geckodriver'
    - chmod +x /usr/bin/geckodriver
    - rm geckodriver-v0.23.0-linux64.tar.gz
    - export PATH=$PATH:/usr/bin
    - echo $PATH
    - SELENIUM="http://selenium__standalone-firefox:4444/wd/hub" BASE_URL="https://pro-deploy-123.netlify.com/login" DRIVER="headless_chrome" python test.py
build:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - dist
  only:
    - master

deploy:
  stage: deploy
  script:
    - npm i -g netlify-cli
    - netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod
  dependencies:
    - build
  only:
    - master
