image: nikolaik/python-nodejs:python3.8-nodejs10
cache:
  untracked: true
  paths:
    - node_modules/

stages:
  - setup
  - test 
  - build
  - deploy

setup:
  stage: setup
  script:
   - export PYTHONPATH=$PWD/backend/lib:$PYTHONPATH
   - npm i
  only:
    - master

test unit:
  stage: test
  script:
    - npm run test
  only:
    - master

test_ui:
  stage: test
  services:
    - selenium/standalone-firefox:latest
  script:
    - pip install selenium==3.141.0
    - pip install bs4
    - export PYTHONPATH=$PWD/backend/lib:$PYTHONPATH
    - echo $pwd
    - SELENIUM="http://selenium__standalone-firefox:4444/wd/hub" BASE_URL="https://pro-deploy-123.netlify.com/login" DRIVER="headless_chrome" python selenium_test.py
    - echo $pwd
build:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - dist
  only:
    - master

deploy:
  stage: deploy
  script:
    - npm i -g netlify-cli
    - netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod
  dependencies:
    - build
  only:
    - master
